apiVersion: v1
kind: Namespace
metadata:
  name: sayhi
  labels:
    istio-injection: enabled
spec:
  finalizers:
    - kubernetes
---
# Notes: you should manually inject secret key of hub on QCloud Web GUI after creating this namespace
